- name: Install RabbitMQ (default Ubuntu version)
  hosts: default
  sudo: true
  tasks:
  - name: install rabbit
    apt: name=rabbitmq-server state=present

  - name: Install RabbitMQ web interface
    command: /usr/sbin/rabbitmq-plugins enable rabbitmq_management

  - name: Rabbit guest access
    copy:
      dest: /etc/rabbitmq/rabbitmq.config
      content: '[{rabbit, [{loopback_users, []}]}].'

  - name: Restart RabbitMQ
    service: name=rabbitmq-server state=restarted
