- name: Install GBIF registry
  hosts: default
  sudo: true
  tasks:
  # Registry webservice and CLI
  - name: Quick setup with a shell script
    script: files/registry.sh

  # Registry console
  - name: installing Java runtime environment
    apt: name=nodejs,apache2 state=present

  - name: Apache for static console
    copy:
      src: /vagrant/provisioning/files/registry-console.vhost
      dest: /etc/apache2/sites-available/000-default.conf

  - name: Install Registry Console
    unarchive:
      src: /vagrant/provisioning/files/registry-console-2019-03-19.tar
      dest: /var/www/html

  - name: Restart Apache HTTPD
    service: name=apache2 state=restarted
